# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WHOOSH' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth’
pod 'Firebase/Database’
 pod 'KeychainSwift'
pod 'Firebase/Storage’

  # Pods for WHOOSH

  target 'WHOOSHTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WHOOSHUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
